[package]
name = "fd-queue"
version = "0.1.0"
authors = ["Steven Bosnick <sbosnick@sympatico.ca>"]
edition = "2018"

[features]
default = ["mio-fd", "net-fd"]
net-fd = ["nix", "tracing"]
mio-fd = ["net-fd", "mio"]

[dependencies]
nix = {version = "0.17.0", optional = true}
tracing = {version = "0.1.15", optional = true}
mio = { version = "0.7.0", optional = true, features = ["os-util"] }

[dev-dependencies]
tempfile = "3.1.0"
assert_matches = "1.3.0"
mio = { version = "0.7.0", features = ["os-poll"] }
