[package]
name = "fd-queue"
version = "0.1.0"
authors = ["Steven Bosnick <sbosnick@sympatico.ca>"]
edition = "2018"

[features]
default = ["mio-fd", "net-fd", "tokio-fd"]
net-fd = ["nix", "tracing"]
mio-fd = ["net-fd", "mio"]
tokio-fd = ["mio-fd", "tokio"]

[dependencies]
nix = {version = "0.17.0", optional = true}
tracing = {version = "0.1.15", optional = true}
mio = {version = "0.6.22", optional = true}
tokio = {version = "0.2.21", optional = true, features = ["io-driver", "io-util"]}
pin-project = "0.4.22"
futures-core = "0.3.5"
futures-util = "0.3.5"

[dev-dependencies]
tempfile = "3.1.0"
assert_matches = "1.3.0"
tokio = {version = "0.2.21", features = ["rt-threaded", "macros"]}
